// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwhropuakbqyhkrfhpce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aHJvcHVha2JxeWhrcmZocGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTI3NTcsImV4cCI6MjA2NTU2ODc1N30.a9zP_0_JZyC79GAnDdq5r51emdDOHKO5H0B8dwWAy9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);